### ISSUE TITLE
Failed to run Coh-Metrix-Esp

### ISSUE THREAD

**Issue by Chunngai** [andreqi/coh-metrix-esp#6]
Hello.

I tried to use Coh-Metrix-Esp with the command below and failed.
```bash
java -jar coh-metrix-esp.jar -i test_esp_cohmetrix.txt -o o.txt
```

The output is:
```
null
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Main.analyzeFile(Main.java:77)
	at Main.main(Main.java:53)
Caused by: java.lang.NullPointerException
	at pucp.edu.cohmetrixesp.utils.NativeUtils.saveLibrary(NativeUtils.java:91)
	at pucp.edu.cohmetrixesp.utils.NativeUtils.loadLibrary(NativeUtils.java:13)
	at pucp.edu.cohmetrixesp.utils.ImplFreelingAnalyzer.<init>(ImplFreelingAnalyzer.java:36)
	at pucp.edu.cohmetrixesp.utils.ImplFreelingAnalyzer.getInstance(ImplFreelingAnalyzer.java:30)
	at pucp.edu.cohmetrixesp.metrics.MetricsEngine.<init>(MetricsEngine.java:18)
	at pucp.edu.cohmetrixesp.metrics.MetricsEngine.<clinit>(MetricsEngine.java:17)
	... 2 more
```

OS: Ubuntu 20.04
FreeLing: 4.2
SWIG: 4.0
JDK: java-8-openjdk-amd64

Do you have any idea what's going wrong?

**Comment by Chunngai** [comment]
I followed the instruction [here](https://github.com/TALP-UPC/FreeLing/blob/v4.2/APIs/java/README.Unix.md). But the file `libfreeling_javaAPI.so` was not generated. That may be the problem.

**Comment by feralvam** [comment]
Hi @Chunngai! Thanks for your interest in CohMetrixEsp. Unfortunately, we currently don't have the bandwidth to provide the necessary support. If you are just interested in computing indices for several texts, I am more than happy to do that for you with my current local working installation. Just [send me an email](mailto:alvamanchegof@cardiff.ac.uk) with the documents in .txt. Alternatively, you could also try [MultiAzterTest](https://github.com/kepaxabier/MultiAzterTest). Apologies for that.

**Comment by Chunngai** [comment]
@feralvam Hello! I managed to compute indices on the macOS system.

You mentioned [MultiAztertest
](https://github.com/kepaxabier/MultiAzterTest) in your answer. It's a great tool and fits my need for calculating a variety of features for Spanish. However, it seems that the related paper has not been published and I cannot cite it in my paper. Are there any similar tools? It would be great if you could provide some information.

Thank you.

**Comment by feralvam** [comment]
Glad to hear that! Just out of curiosity, did you run it in a macbook with an M1 chip? We've had reported issues before when people have tried to run it in those type of machines.

Yeah, unfortunately MultiAzterTest only has an arxiv version. Although the original [AzterTest](http://journal.sepln.org/sepln/ojs/ojs/index.php/pln/article/view/6196) was published in the Procesamiento de Lenguaje Natural journal. There's also the [Text Complexity Library](https://gitlab.ujaen.es/amontejo/text-complexity), but I've never used it.

Hope that helps.

**Comment by Chunngai** [comment]
No, not an M1 chip. And my OS is Catalina. It is currently not fully supported by homebrew, which is required to install FreeLing. But fortunately, it still worked.

And thanks for your suggestions. Can you open the link to the text complexity library? I could not open it.

**Comment by feralvam** [comment]
I can. Their code in on gitlab, btw. There's also a [paper](http://journal.sepln.org/sepln/ojs/ojs/index.php/pln/article/view/6289) for it.

**Comment by Chunngai** [comment]
I can open it now. Thanks for your help and suggestions!
